[window]
startup_mode = "maximized"
opacity = 0.9
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13
[keyboard]
bindings = [{key = "Space", mods = "Shift", action = "ToggleViMode"}, {key = "Escape", mode = "Vi", action = "ToggleViMode"}]
[terminal]
shell = "/usr/bin/bash"
