monitor = ,preffered,auto,1

exec-once = waybar
exec-once = swaync
exec-once = alacritty
exec-once = hyprpaper 
exec-once = copyq
exec-once = pypr
exec-once = flatpak run net.christianbeier.Gromit-MPX --opacity 1.0
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

source = ./variables.conf
source = ./keybinds.conf
source = ./permissions.conf
