bind = SUPER, T, exec, alacritty
bindp = SUPER, C, killactive
bindp = SUPER_SHIFT, C, forcekillactive
bind = SUPER, F, exec, rofi -show drun
bind = , PRINT, exec, hyprshot -m output --clipboard-only
bind = SUPER, PRINT, exec, hyprshot -m region --clipboard-only
bind = SUPER, Q, exec, hyprlock --config $HOME/.config/hypr/hyprlock.conf --quiet
bind = SUPER, P, exec, copyq toggle
bind = SUPER, S, fullscreen, 0 toggle
bind = SUPER_SHIFT, F, togglefloating, active
bind = SUPER_SHIFT, S, centerwindow
bind = SUPER, N, exec, nautilus
bind = SUPER, I, exec, hyprpicker --autocopy

bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

bind = SUPER_SHIFT, h, movewindow, l
bind = SUPER_SHIFT, l, movewindow, r
bind = SUPER_SHIFT, k, movewindow, u
bind = SUPER_SHIFT, j, movewindow, d

bindep = SUPER, EQUAL, resizeactive, 10 0
bindep = SUPER_SHIFT, EQUAL, resizeactive, -10 0
bindep = SUPER, MINUS, resizeactive, 0 10
bindep = SUPER_SHIFT, MINUS, resizeactive, 0 -10

bindm = SUPER, mouse:272, movewindow
bindm = SUPER_SHIFT, mouse:272, resizewindow

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

bind = SUPER_SHIFT, 1, movetoworkspace, 1
bind = SUPER_SHIFT, 2, movetoworkspace, 2
bind = SUPER_SHIFT, 3, movetoworkspace, 3
bind = SUPER_SHIFT, 4, movetoworkspace, 4
bind = SUPER_SHIFT, 5, movetoworkspace, 5
bind = SUPER_SHIFT, 6, movetoworkspace, 6
bind = SUPER_SHIFT, 7, movetoworkspace, 7
bind = SUPER_SHIFT, 8, movetoworkspace, 8
bind = SUPER_SHIFT, 9, movetoworkspace, 9
bind = SUPER_SHIFT, 0, movetoworkspace, 10

# PipeWire ctl stuff
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
