env = XCURSOR_SIZE, 6
env = HYPRCURSOR_SIZE, 6

gesture = 3, horizontal, workspace

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
    no_focus_fallback = true
}

decoration {
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
    dim_modal = true
    blur {
        enabled = true
        size = 2
        passes = 1
        popups = true
    }
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    focus_on_activate = true
    enable_swallow = true
    swallow_regex = ^Alacritty$
}

input {
    kb_layout = us, ru
    kb_options = grp:alt_shift_toggle, grp:win_space_toggle
    follow_mouse = 1
    numlock_by_default = true
    touchpad {
        drag_lock = true
        natural_scroll = true
    }
}

binds {
    workspace_center_on = 1
}

cursor {
    persistent_warps = true
    warp_on_change_workspace = 2
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
    enforce_permissions = true
}

dwindle {
    pseudotile = true
    force_split = 2
    preserve_split = true
}

