name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{ matrix.test_script }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_script:
          - tests/install/boot_configuration_test.sh
          - tests/install/disk_formatting_test.sh
          - tests/install/system_configuration_test.sh
          - tests/system/add_user_test.sh
          - tests/system/install_packages_test.sh
          - tests/system/mirrorlist_test.sh
          - tests/system/misc_test.sh
          - tests/system/self_deploy_test.sh
          - tests/utils/make_sourced_test.sh
          - tests/utils/parse_options_test.sh
          - tests/utils/utils_test.sh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: chmod +x tests/**/*.sh tests/*.sh || true

      - name: Run ${{ matrix.test_script }}
        env:
          ROOT_DIR: ${{ github.workspace }}
        run: bash "${{ matrix.test_script }}"
